version: "2"

services:
  tests:
    image: evonove/ci:latest
    command: tox -r --workdir=/tmp/.toxtrantor-${RANDOM_WD}
    volumes_from:
      - container:jenkins-data
    environment:
      - WORKSPACE
